- cmd/action/docker.go
- cmd/action/docker_test.go
Closes: #XXX
> Add a description of the overall background and high-level changes that this PR introduces
**_Example (remove this)_**
- _The metadata is stored in the blob store on job creation time as a persistent artifact_
- _Deployments RPC transmits only the blob storage reference_
- _Daemons retrieve the RPC data from the blob cache_
> Please pick one of the following options
This change is a trivial rework/code cleanup without any test coverage.
**(or)**
This change is already covered by existing tests, such as _(please describe tests)_.
**(or)**
This change added tests and can be verified as follows:
> feat: add docker helper functions

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- common/tea_cmd/docker_test.go
Closes: DEVOP-73
- _Init CI workflow for build, test (+coverage), and binary release_
- test: execute `go test ..` + upload coverage results to `Codecov.io`
- build: execute `go build ..`
- release: upon Github Release event is created, trigger the test, build, and attach the build binary to Github Release.
- _Released binary can be installed from our self-hosted installer:  `curl https://install.world.dev/cli! | bash`_
- _**Skip the current failed unit test for this CI run, need to address this on separate PR._
- Make sure the test, build, and release workflow runs successfully.
- Create a Github Release, wait for release CI to run, and check if all cross-platform binary is uploaded to the corresponding release.
- On your local device, run `curl https://install.world.dev/cli! | bash`, …
> chore(ci): build, test, release + installer ready

- cmd/cardinal/dev.go
Closes: #496 
When you run `world-cli cardinal dev` then ctrl+C to quit you'll see a wierd error message about how the process already quit then the cli will display the help message. 
this occurs because when scott was messing with the cli he used a version of cardinal that hung during shutdown. So he used a force quit to kill it. 
Now that cardinal handles shutdown properly and doesn't hang forever during start game the mechanism is now changed to wait 10 seconds and see if the cardinal shutsdown by itself. If it doesn't then force quit.
> feat: `world cardinal dev` graceful shutdown

- cmd/world/cardinal/dev.go
Closes: #621
Fixes a race condition. Two things, redis and Cardinal are activated. If Cardinal finishes activating before redis finishes it won't be able to find redis and crash. This is a race condition. This fix makes sure redis will start before cardinal.
> fix(starter-game-template): fix race condition.

- cmd/world/cardinal/cardinal.go
- cmd/world/cardinal/restart.go
- cmd/world/cardinal/start.go
- cmd/world/evm/evm.go
- cmd/world/root/root.go
- common/config/config.go
- common/config/config_test.go
- common/tea_cmd/docker.go
Closes: #WORLD-505
Add commands to start and stop evm and da layer containers.
To start the evm for prod (this will fail to start if some config variables are missing):
```
world evm start
```
To start evm in dev mode (A da layer container will be started and appropriate env variables will be injected into the config)
```
world evm start --dev
```
To stop the evm and da layers:
```
world evm stop
```
I ran manual tests locally after cloning the starter game template. 
The current state of starter-game-template has an incorrect negative block time. It's fixed with this PR: https://github.com/Argus-Labs/starter-game-template/pull/32
> feat(world-cli): Add commands for running evm and da layer

- common/tea_cmd/docker.go
Closes: #628
Docker compose has really good color printing. world-cli when running the command `world cardinal start` actually hides a lot of output and gets rid of the color. This should make everything identical to as if you were running `docker-compose`
Quick PR to help namra debug stuff as the logs with world-cli aren't displaying everything he needs.
> feat(world-cli): This enables better stdout logging for `world cardinal start`

- cmd/world/cardinal/start.go
- example-world.toml
Closes: WORLD-681
Update world-cli to use CARDINAL_LOG_LEVEL env var
Configuration can be added to world.toml or using flag --log-level on 'world cardinal start` command.
> feat: update world-cli to use CARDINAL_LOG_LEVEL env var

- cmd/world/cardinal/create.go
- common/tea_cmd/git.go
- common/tea_cmd/git_test.go
Closes: WORLD-715
Clone latest tags instead of main branch to instead of cloning main the branch. it's to prevent possibility that we might be in the process of updating starter-game-template and it's not ready for consumption yet.
- add command `git rev-list --tags --max-count=1` and `git describe --tags` to get latest tags and checkout
- Modify `GitCloneCmd` func to be able to unit test
Added unit test for `GitCloneCmd` func
> chore(git): clone latest version of starter-game-template

- .github/workflows/test.yml
Closes: #DEVOP-168
Issue: There was a `TestExecuteDoctorCommand` test case that expected a certain output from `doctor` command. This terminal output needs to be captured from `/dev/tty` which by default doesn't exist on GitHub runner. 
- Add a workaround for a missing `/dev/tty` on GitHub-action runner, using `script` to wrap around the `go test` interactive session terminal. 
- CI Test check success.
- TTY workaround discussion: https://github.com/actions/runner/issues/241#issuecomment-577370913
> ci: github runner tty workaround

- cmd/world/cardinal/cardinal.go
- cmd/world/root/create.go
- cmd/world/root/root.go
- cmd/world/root/root_test.go
Closes: WORLD-362
Adding unit test for create, start, stop, purge command
- Added new test that cover create, start, stop, and purge command
Test will do this scenario
- run create command to clone starter-game-template
- start the cardinal
- hit `/health` endpoint and verify the response
- stop the cardinal
- hit `/health` endpoint and make sure it will be error
- purge the cardinal
> test(cardinal): add test for create, start, stop, purge

- cmd/world/cardinal/restart.go
- cmd/world/root/root_test.go
Closes: WORLD-532
Add test for `restart` and `dev` command
- Add Detach mode for restart
- Modify older test, adding restart before stop and purge
- Add new test for dev
- Running the unit test suite
> test: add test on restart and dev command

- cmd/world/cardinal/dev.go
- common/tea_cmd/git.go
- go.mod
- go.sum
Closes: WORLD-871
Change fresh lib to using fork on argus labs repo
run command `world cardinal dev`
> chore: change fresh using argus labs github

- cmd/world/cardinal/dev.go
- cmd/world/root/root_test.go
- common/tea_cmd/docker.go
Closes: WORLD-898
Port change following new cardinal release
> chore: update ports from 3333 -> 4040

- common/tea_cmd/git.go
- common/tea_cmd/git_test.go
Closes: WORLD-897
Renaming go.mod module to be match with game shard name. and rename all import module.
- Covered by previous unit test.
- Run world create and check by running the game shard
> feat: rename go module to be match with shard game name

- cmd/world/main.go
- common/config/config.go
- common/teacmd/git.go
- common/teacmd/git_test.go
- go.mod
- go.sum
Closes: WORLD-990
World CLI generates router key and append it to world.toml file
- create function for appending the section and field to toml file
- create function for generating random hex string
- create unit test for added function
- test the env by running command `world cardinal start`
> feat: append generated router key to world.toml

- .github/workflows/build.yml
- .github/workflows/lint-go.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .gitignore
- .goreleaser.yaml
- makefiles/build.mk
- makefiles/dev.mk
Closes: WORLD-971
- Implement [GoReleaser](https://goreleaser.com/) for build and releasing world-cli binary package.
- Release can be done in two ways:
- Create a manual release from GitHub pages, and CI will trigger the GoReleaser to do the build, upload all the binaries, and add the changelog.
- Or, trigger it locally using `make release <tag-version>`, and it will automatically create the tag, push it, create the release, and upload all the binary builds.
- add GoReleaser config file (.goreleaser.yml)
- update `make build` to use goreleaser cli
- add `make goreleaser-install`
- update CI related workflow for build & release
- fix Posthog API var missmatch on main branch
- add `make release <tag-version>` 
- `make install` & `make clean`
- `make release` 
- handle wrong/incomplete …
> ci: use GoReleaser for build & release binary

- cmd/world/main.go
- cmd/world/root/create.go
- common/globalconfig/globalconfig.go
- common/teacmd/editor.go
- common/teacmd/editor_test.go
- telemetry/posthog.go
Closes: WORLD-999
Sets up Cardinal Editor on `world create`. The set up steps include:
- download the latest release from github
- unzip into `{targetDirectory}/.editor`
- replace all instances of `__CARDINAL_PROJECT_ID__` with a guid
- New step in `world create`
- SetupCardinalEditor function in the `teacmd` package
- Unit tests for it
Added unit test that checks if the editor is setup correct. (though it doesn't check if it works correctly, as the web server isn't implemented yet)
> feat: fetch & download cardinal editor on world create

- cmd/world/cardinal/dev.go
- cmd/world/root/root.go
- common/teacmd/editor.go
Closes: WORLD-1000
Add feature run cardinal on `world cardinal dev`
- add function to serve cardinal editor web files
- add function to find unused port from 3000 to 4000
- add step to run cardinal editor before running redis and cardinal server (it will not block the process if cardinal editor failed to run)
manually tested using `world cardinal dev` command
This will be updated in the next PR
- Check cardinal version to be match with cardinal server
- Setup cardinal editor dir if not exists
> feat: run cadinal editor on dev mode

- .gitignore
- common/globalconfig/globalconfig.go
Closes: WORLD-1020
Previously the `.worldcli` file was used as a cache for the last logged in time for posthog. This file was moved to `.worldcli/last_logged_time`, so the setup function should remove it before creating the `.worldcli` directory.
- delete .worldcli cache file if it exists before creating .worldcli directory
Manually tested & verified
> fix: delete .worldcli cache file if it exists before creating .worldcli directory

- common/teacmd/editor.go
this is just a quick patch fix to a small bug. i opened a linear ticket to address this more thoroughly.  https://linear.app/arguslabs/issue/WORLD-1046/cardinal-cardinal-editor-version-map-in-cli
> fix: quick hotfix to have a default/fallback value for cardinal editor versioning

- common/teacmd/editor.go
- common/teacmd/editor_test.go
- example-world.toml
Closes: WORLD-1046
Make world cli check cardinal editor version mapping to cardinal editor repo
- Create func to fetch version map
- Added unit test for new func
- Tested manually using `world cardinal dev` command
> fix: cardinal editor version mapping

- common/config/config.go
- common/config/config_test.go
Closes: WORLD-1063
Currently, `world cardinal start` will not rebuild the cardinal container when the code has been modified. Either `world cardinal start --build` or `world cardinal start --build=true` needs to be run. This PR makes it so the following 3 commands have the same behavior:
```
world cardinal start
world cardinal start --build
world cardinal start --build=true
```
Ensure the cfg.Build field is set to true by default.
Refactor the config source file to make the precedent ordering more clear. 
To manually test this, checkout this branch and navigate to the `world-cli/cmd/world` directory. Then run:
`go build -o newworld main.go`
This creates an executable called `newworld`. This allows you to compare the behavior of the default `world` behavior to this branch.
Navigate to the …
> fix(world-cli): Ensure the build flag defaults to true

- cmd/world/cardinal/dev.go
- cmd/world/cardinal/start.go
- cmd/world/root/create.go
- common/config/config.go
- common/teacmd/editor.go
Closes: WORLD-1084 & WORLD-1078 & WORLD-1045
Fix find world.toml recursively on parent dir
- load config and get root dir
- change hardcoded chdir using rootdir
- fix return error when file not exist
Manually verified by running `world cardinal dev`
> fix: find world.tom on parent dir

- cmd/world/cardinal/cardinal.go
- cmd/world/cardinal/common_flag.go
- cmd/world/cardinal/dev.go
- cmd/world/cardinal/start.go
- cmd/world/cardinal/util_editor.go
- cmd/world/root/root.go
- cmd/world/root/root_test.go
- common/env.go
- common/logger/init.go
- common/port.go
- common/teacmd/docker.go
- go.mod
- go.sum
- `world cardinal dev` now use pretty logging on latest Cardinal version. This is done by setting `CARDINAL_PRETTY_LOG` to true.
- Refactors to goroutine management in `world cardinal start` and `world cardinal dev` to make it more reliable using error group.
- Disable printing the usage guide when a command returns an error.
- Various string reformatting using lipgloss to make things look pretty.
- Prevent exit code 130, 137, 143 from being treated as an error since it's an expected exit code from Docker when it receives termination signal (i.e. Ctrl + C, SIGKILL, SIGTERM, etc)
- Kill `world cardinal dev --watch` flag because runner is ugly and buggy af
1. Run `world cardinal dev` and `world cardinal start` and try to break it. This includes running it against various edge cases (i.e. …
> feat: cardinal pretty logging, improve goroutine reliability, kill --watch

- common/teacmd/editor.go
Closes: WORLD-1149
When trying to run world cli on windows, there's an issue when exec `world create`. This PR is adjusting the code for windows OS.
- Adjust file close to avoid Access Denied
Manually tested on windows without using WSL
> fix: adjust closing file to make world cli run on windows

- cmd/world/cardinal/cardinal.go
- cmd/world/cardinal/dev.go
- cmd/world/cardinal/purge.go
- cmd/world/cardinal/restart.go
- cmd/world/cardinal/start.go
- cmd/world/cardinal/stop.go
- cmd/world/evm/evm.go
- cmd/world/evm/start.go
- cmd/world/evm/stop.go
- cmd/world/root/create.go
- cmd/world/root/doctor.go
- cmd/world/root/login.go
- cmd/world/root/root.go
- common/logger/init.go
- common/logger/logger.go
- common/teacmd/docker.go
Closes: WORLD-1154
Re enable debug mode with delve on `world cardinal start` with `--debug` flag
- Re activate `--debug` flag
- Add `nakama-debug` container to fix nakama cannot run because `cardinal` is not running
- Tested manually using `world cardinal start --debug` command and delve with vs code
Notes : Unit test failed because https://github.com/Argus-Labs/starter-game-template/pull/51 need to be merged first and create new tag
> fix: re enable debug mode

- cmd/world/cardinal/dev.go
- cmd/world/root/root.go
- common/teacmd/docker.go
Closes: WORLD-XXX
> Description of the overall background and high-level changes that this PR introduces
> feat: use redis in docker compose, remove go mod vendor prepare step

- cmd/world/cardinal/cardinal.go
- cmd/world/cardinal/dev.go
- cmd/world/cardinal/purge.go
- cmd/world/cardinal/restart.go
- cmd/world/cardinal/start.go
- cmd/world/cardinal/stop.go
- cmd/world/evm/start.go
- cmd/world/evm/stop.go
- common/docker/client.go
- common/docker/client_container.go
- common/docker/client_image.go
- common/docker/client_network.go
- common/docker/client_test.go
- common/docker/client_util.go
- common/docker/client_volume.go
- tea/component/multispinner/multispinner.go
- tea/style/util.go
Closes: WORLD-1173
Fix some PR review bug and changes :
- Fixing stuck on `world cardinal dev` command if docker container is not running
- Adjust creating/starting/stopping indicator on world cli
- Make stopping container parallel instead of one by one
- Remove extra letter on container log
- Add context cancelation when checking redis is healthy to fix stuck on `world cardinal dev`
- Add multispinner component to handle process animation and concurrent process / parallel
- Removing first escape ANSI character on container log 
- Adjusted unit test
- Manual Test
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/YO1Dcg4NByYdZHvKXaTq/64dc0f73-aaad-4b7a-85b1-954cd6a2e194.mov">
</a>
</div>
<video …
> fix: container log, parallel execution, code dupe and process stuck

- cmd/world/cardinal/cardinal.go
- cmd/world/cardinal/common_flag.go
- cmd/world/cardinal/start.go
- cmd/world/evm/evm.go
- cmd/world/root/root.go
- common/config/config.go
- common/config/config_test.go
- common/docker/client_container.go
- common/docker/client_image.go
- common/docker/service/cardinal.go
- common/docker/service/evm.go
- common/docker/service/redis.go
- common/logger/init.go
Closes: WORLD-1196, WORLD-1205, WORLD-1206, WORLD-1207
Fix bug findings on world cli v1.3.1-Beta4
- Fix docker image not builded without exec `world cardinal purge` firs. it's because container need to be removed first so that docker create new container with new image
- Remove red and yellow color for container name
- Fix `--log-level` flag not functioned properly, it's because the envar is not passed to the docker env.
- Move `-v` and `-c` from global flags to only flag in 3rd subcommand
- Add help for `--log-level` value (ex : info, debug, etc)
- Manually tested
- Still covered by unit test
> fix: bug finding on ui/ux and docker built image issue

- cmd/world/forge/common.go
- cmd/world/forge/forge.go
- cmd/world/forge/organization.go
- cmd/world/forge/project.go
Closes: WORLD-1324
Add `world forge organization invite` command to invite user to organization
- added new func to call invite user to org API
Manually test by running `world forge organization invite` command
> feat: invite user to organization

- cmd/world/forge/forge.go
Closes: PLAT-245, PLAT-246
> Description of the overall background and high-level changes that this PR introduces
> fix: proper help for `forge`, `user` and other subcommands
